### PR TITLE
Changes for ubuntu 22.04

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
This is a pair of patches that enables the ext directory to compile on ubuntu 22.04. No further testing has happened.

I especially dislike that i had to replace QMap in some parts of the generator, since that points towards a bug inside there instead of how it is used here. The problem manifests itself as broken internal data inside the QMaps structures. Especially funny(not) was the tree where some node pointed to itself, or the other node that pointed to some random invalid location.

@doudou what is the method to have autoproj/bundler use my personal github repository as a source, so i can actually try to run programs with these changed bindings?

### CODE REVIEW

**Comment by doudou** [comment]
Modify the osdeps or add a new one in autoproj/. See the last example of https://www.rock-robotics.org/rock-and-syskit/workspace/os_dependencies.html#the-rubygem-package-manager.

**Comment by doudou** [comment]
> Finally got around to figure out why QMap breaks: The current linker changed behaviour around -Bsymbolic* and --dynamic-list, leading to the QMapData::shared_null not being exported from the shared object, leading to the shared_null existing twice, which makes comparison against it fail at times.

Oh my ...

**Comment by doudou** [comment]
> Closing here for now until the qt4 debian packages have been fixed.

What fix have you applied on the debian packages ?

**Comment by pierrewillenbrockdfki** [comment]
> > Closing here for now until the qt4 debian packages have been fixed.
> 
> What fix have you applied on the debian packages ?

There is a workaround which simply adds --dynamic-link-data(to src/corelib/corelib.pro, src/gui/gui.pro which are the only libraries affected), see also the discussion at https://sourceware.org/bugzilla/show_bug.cgi?id=26018 . Anna is currently looking into integrating that into our packages.

**Pull request closed without merging**
